assignment1: time Class Reference
time Class Reference
manages hours and minutes in program
#include <time.h>
Public Member Functions
time ()
overload input and output to show, store all time info
time (int hh, int mm)
~time ()
void setTime (int hr, int mm)
store hour and minute to program
void setHour (int hr)
store hour to program
void setMin (int mm)
store minute to program
void print ()
int getHour () const
extract hour from program
int getMin () const
extract minute from program
Private Attributes
int Hour
show hour and minute to program
int Min
minute in data
Detailed Description
manages hours and minutes in program
Definition at line 16 of file time.h.
Constructor & Destructor Documentation
time() [1/2]
time::time ()
overload input and output to show, store all time info
set default value for hour and minute
Definition at line 8 of file time.cpp.
 {
     Hour = 0; Min = 0;
 }
References Hour, and Min.
time() [2/2]
time::time (int hh, int mm)
set hour and min
Parameters
hh - hour, mm - minute
Definition at line 18 of file time.cpp.
{
     Hour = hr;
     Min = mm;
 }
References Hour, and Min.
~time()
time::~time ()
Definition at line 13 of file time.cpp.
             {
 }
Member Function Documentation
getHour()
int time::getHour () const
extract hour from program
Returns
int
Definition at line 41 of file time.cpp.
{
     return Hour;
 }
References Hour.
Referenced by Unit_test().
getMin()
int time::getMin () const
extract minute from program
Returns
int
Definition at line 44 of file time.cpp.
{
     return Min;
 }
References Min.
Referenced by Unit_test().
print()
void time::print ()
Definition at line 38 of file time.cpp.
                  {
     cout << "hour: " << Hour << " min: " << Min;
 }
References Hour, and Min.
Referenced by Unit_test().
setHour()
void time::setHour (int hr)
store hour to program
Parameters
hr - hour
Definition at line 24 of file time.cpp.
{
     Hour = hr;
 }
References Hour.
Referenced by Unit_test().
setMin()
void time::setMin (int mm)
store minute to program
Parameters
mm - minute
Definition at line 27 of file time.cpp.
{
     Min = mm;
 }
References Min.
Referenced by Unit_test().
setTime()
void time::setTime (int hr, int mm)
store hour and minute to program
Parameters
hr - hour, mm - minute
Definition at line 31 of file time.cpp.
{
     Hour = hr;
     Min = mm;
 }
References Hour, and Min.
Referenced by SplitString().
Member Data Documentation
Hour
int time::Hour private
show hour and minute to program
Returns
voidhour in data
Definition at line 73 of file time.h.
Referenced by getHour(), print(), setHour(), setTime(), and time().
Min
int time::Min private
minute in data
Definition at line 75 of file time.h.
Referenced by getMin(), print(), setMin(), setTime(), and time().
The documentation for this class was generated from the following files:
lab 5/time.h
lab 5/time.cpp