assignment1: date Class Reference
date Class Reference
manages date, month, year data in program
#include <date.h>
Public Member Functions
date ()
overload input and output to show, store all date info
date (int dd, int mm, int yyyy)
set date month year
~date ()
void setDay (int dd)
store date to program
void setMonth (int mm)
store month to program
void setYear (int yyyy)
store year to program
void setDate (int dd, int mm, int yyyy)
store date, month, year to program
void print ()
extract date,month,year from program
int getDay () const
extract date from program
int getMonth () const
extract month from program
int getYear () const
extract year from program
Private Attributes
int Date
date of recorded data
int Month
month of recorded data
int Year
year of recorded data
Detailed Description
manages date, month, year data in program
Definition at line 16 of file date.h.
Constructor & Destructor Documentation
date() [1/2]
date::date ()
overload input and output to show, store all date info
Definition at line 9 of file date.cpp.
 {
     Date = 0;
     Month = 0;
     Year = 0;
 }
References Date, Month, and Year.
date() [2/2]
date::date (int dd, int mm, int yyyy)
set date month year
Parameters
dd - date, mm - month, yyyy - year from dataset
Definition at line 20 of file date.cpp.
{
     Date = dd;
     Month = mm;
     Year = yyyy;
 }
References Date, Month, and Year.
~date()
date::~date ()
Definition at line 16 of file date.cpp.
             {
 }
Member Function Documentation
getDay()
int date::getDay () const
extract date from program
Returns
int
Definition at line 46 of file date.cpp.
{
     return Date;
 }
References Date.
Referenced by Unit_test().
getMonth()
int date::getMonth () const
extract month from program
Returns
int
Definition at line 49 of file date.cpp.
{
     return Month;
 }
References Month.
Referenced by menuOption1(), Process_data(), and Unit_test().
getYear()
int date::getYear () const
extract year from program
Returns
int
Definition at line 52 of file date.cpp.
{
     return Year;
 }
References Year.
Referenced by menuOption1(), Process_data(), and Unit_test().
print()
void date::print ()
extract date,month,year from program
Definition at line 43 of file date.cpp.
                  {
     cout << "date: " << Date << " month: " << Month << " year: " << Year;
 }
References Date, Month, and Year.
Referenced by Unit_test(), and Unit_test3().
setDate()
void date::setDate (int dd, int mm, int yyyy)
store date, month, year to program
Parameters
dd - date, mm - month, yyyy - year in dataset
Returns
void
Definition at line 36 of file date.cpp.
{
     Date = dd;
     Month = mm;
     Year = yyyy;
 }
References Date, Month, and Year.
Referenced by SplitString(), and Unit_test3().
setDay()
void date::setDay (int dd)
store date to program
Parameters
dd - date in dataset
Returns
void
Definition at line 27 of file date.cpp.
{
     Date = dd;
 }
References Date.
Referenced by Unit_test().
setMonth()
void date::setMonth (int mm)
store month to program
Parameters
mm - month in dataset
Returns
void
Definition at line 30 of file date.cpp.
{
     Month = mm;
 }
References Month.
Referenced by Unit_test().
setYear()
void date::setYear (int yyyy)
store year to program
Parameters
yyyy - year in dataset
Returns
void
Definition at line 33 of file date.cpp.
{
     Year = yyyy;
 }
References Year.
Referenced by Unit_test().
Member Data Documentation
Date
int date::Date private
date of recorded data
Definition at line 82 of file date.h.
Referenced by date(), getDay(), print(), setDate(), and setDay().
Month
int date::Month private
month of recorded data
Definition at line 84 of file date.h.
Referenced by date(), getMonth(), print(), setDate(), and setMonth().
Year
int date::Year private
year of recorded data
Definition at line 86 of file date.h.
Referenced by date(), getYear(), print(), setDate(), and setYear().
The documentation for this class was generated from the following files:
lab 5/date.h
lab 5/date.cpp