assignment1: Vector< T > Class Template Reference
Vector< T > Class Template Reference
manages Vector template functions and data in it
#include <Vector.h>
Public Member Functions
Vector (int length=DEFAULT_SIZE)
~Vector ()
int Size ()
int isEmpty ()
void push_back (T item)
T & at (int i)
void pop ()
int getMaxLen ()
Private Member Functions
void resize (int newSize)
Private Attributes
T * list
int len
int maxLen
Detailed Description
template<class T>
class Vector< T >
manages Vector template functions and data in it
Date
25/06/2019
Definition at line 13 of file Vector.h.
Constructor & Destructor Documentation
Vector()
template<class T > Vector< T >::Vector (int length = DEFAULT_SIZE)
Definition at line 40 of file Vector.h.
 {
     if (length <= 0)
     {
         cout << "Vector size must be positive" << endl;
         maxLen = DEFAULT_SIZE;
     }
     else {
         maxLen = length;
     }
     len = 0;// Vector is empty at first
     list = new T[maxLen];
 }
References Vector< T >::len, Vector< T >::list, and Vector< T >::maxLen.
~Vector()
template<class T > Vector< T >::~Vector ()
Definition at line 55 of file Vector.h.
 {
     if (list != nullptr)
     {
         delete[] list;
         list = nullptr;
     }
 }
References Vector< T >::list.
Member Function Documentation
at()
template<class T > T & Vector< T >::at (int i)
Definition at line 103 of file Vector.h.
 {
     if ((i >= 0) && (i < len))
     {
         return list[i];
     }
     //default return 1st element
     return list[0];
 }
References Vector< T >::len, and Vector< T >::list.
Referenced by menuOption1(), Print_partData(), Process_data(), and Unit_test3().
getMaxLen()
template<class T> int Vector< T >::getMaxLen () inline
Definition at line 29 of file Vector.h.
 { return maxLen; };
Referenced by Unit_test3().
isEmpty()
template<class T> int Vector< T >::isEmpty () inline
Definition at line 20 of file Vector.h.
 { return len == 0; };
pop()
template<class T > void Vector< T >::pop ()
Definition at line 92 of file Vector.h.
 {
     //resize
     if (len < maxLen /2)
     {
         Vector::resize(maxLen / 2);
     }
     len--;
 }
push_back()
template<class T > void Vector< T >::push_back (T item)
Definition at line 81 of file Vector.h.
 {
     if (len >= maxLen / 2)
     {
         //resize();
         Vector::resize(maxLen * 2);
     }
     list[len++] = item;
 }
References Vector< T >::len, Vector< T >::list, Vector< T >::maxLen, and Vector< T >::resize().
Referenced by ReadFile(), and Unit_test3().
resize()
template<class T > void Vector< T >::resize (int newSize) private
Definition at line 65 of file Vector.h.
 {
     T* newList = new T[maxLen];
     T* newListP = newList;
     T* oldListP = list;
     while (oldListP != (list + len)) {//while != last address of list
         *(newListP) = *(oldListP);
         newListP++;//move to next location/address
         oldListP++;
     }//this loop swap value until the last location of list
     maxLen = newSize;
     delete[] list;
     list = newList;
 }
References Vector< T >::len, Vector< T >::list, and Vector< T >::maxLen.
Referenced by Vector< T >::push_back().
Size()
template<class T> int Vector< T >::Size () inline
Definition at line 19 of file Vector.h.
 { return len; };
References Vector< T >::len.
Referenced by menuOption1(), Process_data(), and Unit_test3().
Member Data Documentation
len
template<class T> int Vector< T >::len private
Definition at line 33 of file Vector.h.
Referenced by Vector< T >::at(), Vector< T >::push_back(), Vector< T >::resize(), Vector< T >::Size(), and Vector< T >::Vector().
list
template<class T> T* Vector< T >::list private
Definition at line 32 of file Vector.h.
Referenced by Vector< T >::at(), Vector< T >::push_back(), Vector< T >::resize(), Vector< T >::Vector(), and Vector< T >::~Vector().
maxLen
template<class T> int Vector< T >::maxLen private
Definition at line 34 of file Vector.h.
Referenced by Vector< T >::push_back(), Vector< T >::resize(), and Vector< T >::Vector().
The documentation for this class was generated from the following file:
lab 5/Vector.h