assignment1: lab 5/unit_testing_file.cpp File Reference
unit_testing_file.cpp File Reference
#include <iostream>
#include <fstream>
#include "date.h"
#include "time.h"
#include "Vector.h"
Functions
int Unit_test ()
int Unit_test2 ()
int Unit_test3 ()
int Unit_test5 ()
Function Documentation
Unit_test()
int Unit_test ()
Definition at line 61 of file unit_testing_file.cpp.
                 {
     //set value into objects
     //passed
     time timeobj;
     date dateobj;
     cout << "test the cimpliler of buggy vccomm " << endl << endl;
     timeobj.setHour(12); timeobj.setMin(04); timeobj.getHour();
     dateobj.setDay(42); dateobj.setMonth(23); dateobj.setYear(3285);
     cout << "show timeobj value: " << timeobj.getHour(); cout << " " << timeobj.getMin();
     cout << "\nshow dateobj value: " << dateobj.getDay(); cout << " " << dateobj.getMonth(); cout << " " << dateobj.getYear();
     cout << endl;
     timeobj.print();
     cout << endl;
     dateobj.print();
     cout << "\nend..." << endl;
     return 0;
 }
References date::getDay(), time::getHour(), time::getMin(), date::getMonth(), date::getYear(), time::print(), date::print(), date::setDay(), time::setHour(), time::setMin(), date::setMonth(), and date::setYear().
Unit_test2()
int Unit_test2 ()
Definition at line 81 of file unit_testing_file.cpp.
                  {
     //this is very useful snippet to avoid GIGO
     //passed
     string filename;
     ifstream input; ofstream output_file;
     //system("dir");
     //test small file
     input.open("data/MetData_Mar01-2014-Mar01-2015-ALL.csv");// data/MetData_Mar01-2014-Mar01-2015-ALL.csv for full test. MetData-31-3.csv
     input.ignore(500, '\n'); //skip 1st line, till end of line
     //cout << input.peek();
     while (!input.eof()) {
         string temp;
         getline(input, temp, '\n');
         cout << temp << endl;// output till end of line
     }
     return 0;
     //just ~ cat data/MetData-31-3.csv (-.-)
 }
Unit_test3()
int Unit_test3 ()
Definition at line 100 of file unit_testing_file.cpp.
                  {
     //this test vector function
     //passed
     Vector<int> intArray;
     intArray.push_back(1758);
     cout << intArray.getMaxLen() << endl;//expected 3 - default value
     intArray.push_back(12);
     cout << intArray.getMaxLen() << endl;//expected 6 - double max length
     cout << " " << intArray.Size() << endl;//expect 2
     intArray.push_back(98);
     intArray.push_back(1758);
     cout << intArray.getMaxLen() << endl;//expected 12 - double max length
     intArray.push_back(15);
     cout << " " << intArray.Size() << endl;//expect 5
     intArray.push_back(98);
     cout << intArray.at(4) << endl;//expect 15 or 1758
     Vector<date> dateArr;
     date dateTemp;
     dateTemp.setDate(12, 7, 5673);
     dateArr.push_back(dateTemp);
     cout << dateArr.getMaxLen() << endl;//expected 3 - default value
     dateTemp.setDate(01, 12, 1925);
     dateArr.push_back(dateTemp);
     cout << dateArr.getMaxLen() << endl;//expected 6 - doubled
     dateTemp.setDate(27, 1, 1999);
     dateArr.push_back(dateTemp);
     cout << " " << dateArr.Size() << endl;//expect 3
     dateArr.at(1).print();//expect day: 1 month: 12 year: 1925
     return 0;
 }
References Vector< T >::at(), Vector< T >::getMaxLen(), date::print(), Vector< T >::push_back(), date::setDate(), and Vector< T >::Size().
Unit_test5()
int Unit_test5 ()
Definition at line 160 of file unit_testing_file.cpp.
                  {
     //process, split raw string
     //passed
     string raw_data = "12/23/5754 16:23, 35,7,34,9.2,45,1,,\n13/3/1256 4:2,";
     string un_process_string = "12/23/5754 16:23, 35,7,34,9.2,45,1,,";
     cout << un_process_string.find("3") << endl;//get 1st orcurrence of " " -expect 4
     cout << un_process_string.substr(0, un_process_string.find("/")) << endl;//expect 12
     un_process_string = un_process_string.substr(un_process_string.find("/"), un_process_string.size());//this remove the readed part
     cout << un_process_string.substr(0, un_process_string.find(",")) << endl;//expect /23/7554 16:23
     un_process_string = un_process_string.substr(un_process_string.find(","), un_process_string.size());
     //singleLine.substr(0, singleLine.find(",");
     cout << un_process_string;
     return 0;
 }